name: Format Check

on:
  pull_request:
    branches: [ master ]
    types: [ assigned, opened, synchronize ]

jobs:
  scala-format-check:
    name: Scala Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"

      - name: Run scalafmt And Print Diff
        continue-on-error: true
        run: sbt scalafmt scalafmtSbt && git diff --exit-code