name: CD Scala

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and deploy jar file
    runs-on: ubuntu-22.04
    environment: DEV
    defaults:
      run:
        working-directory: bigfiles
    strategy:
      matrix:
        include:
          - scala: 2.12.17
            scalaShort: "2.12"
          - scala: 2.11.12
            scalaShort: "2.11"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: "adopt@1.8"

      - name: Build jar for Scala ${{ matrix.scala }}
        run: sbt ++${{ matrix.scala }} assembly

      - name: Create staging directory
        run: mkdir -p staging

      - name: Copy jar to staging
        run: |
          jar_file=$(ls target/scala-${{ matrix.scalaShort }}/dataset-comparison-*.jar)
          base_name=$(basename $jar_file)
          cp target/scala-${{ matrix.scalaShort }}/dataset-comparison-*.jar staging/scala-${{ matrix.scalaShort }}$base_name
          echo "artifact_name=scala-${{ matrix.scalaShort }}$base_name" >> $GITHUB_ENV
          ls staging

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_name }}
          path: bigfiles/staging

      - name: Aquasec Manifest Generation
        run: |
          export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
          if ! cat install.sh.checksum | sha256sum --check; then
          echo "install.sh checksum failed"
          exit 1
          fi
          BINDIR="." sh install.sh
          rm install.sh install.sh.checksum
          ./billy generate \
            --access-token "${{ secrets.GITHUB_TOKEN }}" \
            --aqua-key "${{ secrets.AQUA_KEY }}" \
            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
            --cspm-url https://eu-1.api.cloudsploit.com \
            --artifact-path "${{ github.workspace }}"