name: CI Scala

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    env:
      overall: 0.0
      changed: 80.0
    defaults:
      run:
        working-directory: bigfiles
    strategy:
      matrix:
        include:
          - scala: 2.12.17
            scalaShort: "2.12"
          - scala: 2.11.12
            scalaShort: "2.11"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: "adopt@1.8"

      - name: Build and run tests
        continue-on-error: true
        id: jacocorun
        run: sbt ++${{ matrix.scala }} jacoco

      - name: Add coverage to PR
        if: steps.jacocorun.outcome == 'success'
        id: jacoco-coverage
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/bigfiles/target/scala-${{ matrix.scalaShort }}/jacoco/report/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: ${{ env.overall }}
          min-coverage-changed-files: ${{ env.changed }}
          title: JaCoCo code coverage report - scala ${{ matrix.scala }}
          update-comment: true

      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco-coverage.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco-coverage.outputs.coverage-changed-files }}"

      - name: Fail PR if changed files coverage is less than ${{ env.changed }}%
        if: ${{ steps.jacoco-coverage.outputs.coverage-changed-files < 80.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Changed files coverage is less than ${{ env.changed }}%!')

      - name: Aquasec Manifest Generation
        run: |
          export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
          if ! cat install.sh.checksum | sha256sum --check; then
          echo "install.sh checksum failed"
          exit 1
          fi
          BINDIR="." sh install.sh
          rm install.sh install.sh.checksum
          ./billy generate \
            --access-token "${{ secrets.GITHUB_TOKEN }}" \
            --aqua-key "${{ secrets.AQUA_KEY }}" \
            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
            --cspm-url https://eu-1.api.cloudsploit.com \
            --artifact-path "${{ github.workspace }}"

  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bigfiles
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: "adopt@1.8"

      - name: Run scalafmt And Print Diff
        continue-on-error: false
        run: sbt scalafmt scalafmtSbt && git diff --exit-code
